drill:
  play-sound: true
  use-countdown: true
  timer: 259200
  update-interval: 30
  material: NETHERITE_PICKAXE
  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ᴘɪᴄᴋᴀхᴇ"
  lore:
    - "&7Breaks 9 Blocks at Once"
    - "&8Self Destruct: "
    - "&8%countdown%"
  enchantments:
    EFFICIENCY: 5
    UNBREAKING: 3
    MENDING: 1
  radius:
    x: 1
    y: 1
    z: 0

  disabled-blocks:
    - BARRIER
    - BEDROCK
    - OBSIDIAN
  particle:
    type: REDSTONE
    color:
      r: 128
      g: 0
      b: 128
    count: 10
  sound: BLOCK_AMETHYST_BLOCK_HIT

sellaxe:
  play-sound: true
  use-countdown: true
  timer: 259200
  update-interval: 30
  material: NETHERITE_AXE
  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ѕᴇʟʟ ᴀхᴇ"
  lore:
    - "&7Instantly Sells All Items in A Chest"
    - "&8Self Destruct: "
    - "&8%countdown%"
  enchantments:
    EFFICIENCY: 5
    UNBREAKING: 3
    MENDING: 1
  radius:
    x: 1
    y: 1
    z: 0

  disabled-blocks:
    - BARRIER
    - BEDROCK
    - OBSIDIAN
  particle:
    type: REDSTONE
    color:
      r: 128
      g: 0
      b: 128
    count: 10
  sound: BLOCK_AMETHYST_BLOCK_HIT

axe:
  destory-leaves: true
  use-countdown: true
  timer: 259200
  material: NETHERITE_AXE
  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ᴀхᴇ"
  lore:
    - "&7Breaks Trees Instantly"
    - "&8Self Destruct: "
    - "&8%countdown%"
  enchantments:
    EFFICIENCY: 5
    UNBREAKING: 3
    MENDING: 1
  particle:
    type: REDSTONE
    color:
      r: 255
      g: 165
      b: 0
    count: 10

shovel:
  use-countdown: true
  timer: 259200
  material: NETHERITE_SHOVEL
  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ѕʜᴏᴠᴇʟ"
  lore:
    - "&79 Blocks Per Break"
    - "&8Self Destruct: "
    - "&8%countdown%"
  enchantments:
    EFFICIENCY: 5
    UNBREAKING: 3
    MENDING: 1
  disabled-blocks:
    - BARRIER
    - BEDROCK
  particle:
    type: REDSTONE
    color:
      r: 0
      g: 255
      b: 255
    count: 10
  radius:
    x: 1
    y: 1
    z: 0

bucket:
  use-countdown: true
  material: BUCKET
  timer: 259200
  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ʙᴜᴄᴋᴇᴛ"
  lore:
    - "&7Drains 27 Water At Once"
    - "&8Self Destruct:"
    - "&8%countdown%"
  enchantments:
    UNBREAKING: 3
  hide-enchantments: true
  remove-radius:
    x: 2
    y: 2
    z: 2
  disabled-blocks: []

shardbooster:
  use-countdown: false
  material: POTION
  timer: 86400
  multiplier: 4
  display-name: "&dѕʜᴀʀᴅ ʙᴏᴏѕᴛᴇʀ"
  lore:
    - "&f4x Shard Production for 24 hours"
    - "&8Self Destruct:"
    - "&8%countdown%"
  potion-color: "8B5CF6"
  activation-sound: ENTITY_PLAYER_LEVELUP
  activation-message: "&aYou have activated your &dShard Booster&a for 24h."

multitool:
  use-countdown: true
  material: NETHERITE_AXE
  timer: 259200

  display-name: "&dᴀᴍᴇᴛʜʏѕᴛ ᴍᴜʟᴛɪᴛᴏᴏʟ"
  lore:
    - "&7Every Tool Inside a Tool"
    - "&8Self Destruct: "
    - "&8%countdown%"

  enchantments:
    UNBREAKING: 3
    EFFICIENCY: 5
    MENDING: 1

  pickaxe: NETHERITE_PICKAXE
  axe: NETHERITE_AXE
  shovel: NETHERITE_SHOVEL
  pickaxe-blocks:
    - STONE
    - COBBLESTONE
    - DIORITE
    - GRANITE
    - ANDESITE
    - COAL_ORE
    - IRON_ORE
    - GOLD_ORE
    - REDSTONE_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - NETHERRACK
    - DEEPSLATE
    - COPPER_ORE
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_GOLD_ORE
    - DEEPSLATE_COPPER_ORE
    - DEEPSLATE_REDSTONE_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DEEPSLATE_EMERALD_ORE
    - TERRACOTTA
    - OBSIDIAN
    - END_STONE
    - END_STONE_BRICKS
    - PRISMARINE
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - QUARTZ_ORE
    - NETHER_QUARTZ_ORE
    - ANCIENT_DEBRIS
    - BASALT
    - POLISHED_BASALT
    - BLACKSTONE
    - POLISHED_BLACKSTONE
    - TUFF
    - CALCITE
    - DRIPSTONE_BLOCK
    - SCULK
    - SCULK_CATALYST
    - SCULK_SENSOR
    - SCULK_SHRIEKER
    - SCULK_VEIN
    - IRON_BLOCK
    - GOLD_BLOCK
    - DIAMOND_BLOCK
    - EMERALD_BLOCK
    - REDSTONE_BLOCK
    - LAPIS_BLOCK
    - COAL_BLOCK
    - COPPER_BLOCK
    - NETHERITE_BLOCK

  axe-blocks:
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - MANGROVE_LOG
    - CHERRY_LOG
    - BAMBOO_BLOCK
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_CHERRY_LOG
    - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - JUNGLE_WOOD
    - ACACIA_WOOD
    - DARK_OAK_WOOD
    - MANGROVE_WOOD
    - CHERRY_WOOD
    - CRIMSON_STEM
    - WARPED_STEM
    - CRIMSON_HYPHAE
    - WARPED_HYPHAE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MANGROVE_PLANKS
    - CHERRY_PLANKS
    - BAMBOO_PLANKS
    - BOOKSHELF
    - LECTERN
    - CRAFTING_TABLE
    - BARREL
    - CHEST
    - TRAPPED_CHEST
    - FLETCHING_TABLE
    - LOOM
    - COMPOSTER
    - CARTOGRAPHY_TABLE
    - SMITHING_TABLE
    - NOTE_BLOCK
    - JUKEBOX
    - LADDER

  shovel-blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    - SAND
    - RED_SAND
    - GRAVEL
    - CLAY
    - SNOW
    - SNOW_BLOCK
    - SOUL_SAND
    - SOUL_SOIL
    - MYCELIUM
    - GRASS_PATH
    - COARSE_DIRT
    - ROOTED_DIRT
    - MUD
    - FARMLAND
    - SUSPICIOUS_SAND
    - SUSPICIOUS_GRAVEL
    - POWDER_SNOW
    - MOSS_BLOCK
    - MOSS_CARPET
