interval: 60
amount: 2
permission: "prism.shards.passive"

# Kill Reward Configuration
kill-reward:
  amount: 3
  cooldown: 300

# Messages
messages:
  passive:
    chat: "&7You have received &5{shard} prisms."
    actionbar: "&7You have received &5{shard} prisms."
  active:
    actionbar: "&5+{shards} prisms&7 for killing &f{PLAYER}"

# Sounds
sounds:
  passive: "BLOCK_AMETHYST_BLOCK_CHIME"      