ping-message:
  - "&d&lᴘʀɪѕᴍsᴍᴘ"
  - "&4&lᴜɴᴅᴇʀ ᴍᴀɪɴᴛᴇɴᴀɴᴄᴇ"

disconnect-message:
  - "&d&lᴘʀɪѕᴍsᴍᴘ"
  - ""
  - "&fThe server is currently undergoing maintenance."
  - "&7We are pushing updates to improve your experience."
  - ""
  - "&fCheck the discord for more information."
  - "&9discord.gg/psmp"