enabled: true
port: 12001
api_key: "sk-YziIK3AdUmroqmquJrshwJclNQ3dl8qNrSnXBuuBvPOQ1dAf"
region: "Europe"

# GET /players/offend/?search={BANID}
# GET /players/offend/playerlive
# GET /players/filter/playerlive
# GET /players/commands/playerlive
# GET /players/signs/playerlive
# GET /players/stats/onlineplayers
# GET /players/stats/?player=gamertag
# GET /players/money/?player=<name>
# GET /players/shards/?player=<name>
# GET /players/blocks_break/?player=<name>
# GET /players/blocks_placed/?player=<name>
# GET /players/mobs_killed/?player=<name>
# GET /players/kill/?player=<name>
# GET /players/death/?player=<name>
# GET /leaderboard/money/list
# GET /leaderboard/shards/list

# POST /players/offend/unban?player=<NAME>
# POST /players/offend/ban?player=<NAME>&reason=<REASON>&duration=<DURATION>