title: "&dᴀꜰᴋ"
subtitle: "&fEarn one shard per minute"
actionbar: "&7Next shard in &d<COUNTDOWN>s"
countdown: 60
reward-amount: 1

entry-sound:
  sound: "minecraft:block.amethyst_block.chime"
  volume: 15.0
  pitch: 1.0
